CREATE TABLE `ats_test` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(64) NULL DEFAULT NULL,
	`DESCRIPTION` VARCHAR(64) NULL DEFAULT NULL,
	`CREATED_AT` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);
